// Counter
export const GET_COUNTER_VALUE = 'GET_COUNTER_VALUE';
export const SET_COUNTER_VALUE = 'SET_COUNTER_VALUE';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_RESET = 'COUNTER_RESET';
export const COUNTER_FAILURE = 'COUNTER_FAILURE';


export const GET_PLACES = 'GET_PLACES';
export const SET_PLACES = 'SET_PLACES';
export const PLACES_FAILURE = 'PLACES_FAILURE';
